apiVersion: migration.openshift.io/v1alpha1
kind: MigPlan
metadata:
  name: default-migplan
  namespace: velero
spec:
  destMigClusterRef:
    name: host
    namespace: velero
  srcMigClusterRef:
    name: source-cluster
    namespace: velero
  indirectImageMigration: true
  indirectVolumeMigration: true
  migStorageRef:
    name: gcp-bucket
    namespace: velero
  namespaces:
    - cluster-migrate-test-app
  persistentVolumes:
    - capacity: 5Gi
      name: pvc-d99c1a3d-c526-45b7-8572-5507d8bdd7b0
      storageClass: csi-sc-viettelplugin-ssd
      pvc:
        accessModes:
          - ReadWriteOnce
        hasReference: true
        name: pvc-demo
        namespace: cluster-migrate-test-app
      selection:
        action: copy
        copyMethod: filesystem
        storageClass: csi-sc-viettelplugin-ssd
      supported:
        actions:
          - copy
        copyMethods:
          - filesystem
    - capacity: 5Gi
      name: spec-nfs-pv
      storageClass: static-nfs-sc
      pvc:
        accessModes:
          - ReadWriteMany
        hasReference: true
        name: spec-nfs-pvc
        namespace: cluster-migrate-test-app
      selection:
        action: move
        storageClass: static-nfs-sc
      supported:
        actions:
          - copy
          - move
          - skip
        copyMethods:
          - filesystem
          - snapshot
    - capacity: 5Gi
      name: pvc-f70deda4-48a9-4035-8ee3-3073c8e2cd67
      storageClass: csi-nfs-sc
      pvc:
        accessModes:
          - ReadWriteMany
        hasReference: true
        name: csi-nfs-pvc
        namespace: cluster-migrate-test-app
      selection:
        action: copy
        copyMethod: snapshot
        storageClass: csi-nfs-sc
      supported:
        actions:
          - copy
          - move
          - skip
        copyMethods:
          - filesystem
          - snapshot
