apiVersion: migration.openshift.io/v1alpha1
kind: MigStorage
metadata:
  name: vtc-bucket
  namespace: velero
spec:
  backupStorageConfig:
    awsBucketName: thanhph3-migrate
    awsS3Url: "https://os.viettelcloud.vn"
    awsRegion: "vn-central-1"
    awsS3ForcePathStyle: true
    credsSecretRef:
      name: aws-credentials
      namespace: velero
  backupStorageProvider: aws