apiVersion: migration.openshift.io/v1alpha1
kind: MigStorage
metadata:
  name: gcp-bucket
  namespace: velero
spec:
  backupStorageConfig:
    gcpBucket: mig-controller-demo
    credsSecretRef:
      name: gcp-credentials
      namespace: velero
  backupStorageProvider: gcp