apiVersion: migration.openshift.io/v1alpha1
kind: MigStorage
metadata:
  name: gcp-bucket
  namespace: mig-operator
spec:
  backupStorageConfig:
    gcpBucket: mig-controller-demo
    credsSecretRef:
      name: gcp-credentials
      namespace: mig-operator
  backupStorageProvider: gcp