apiVersion: v1
kind: Secret
metadata:
  namespace: velero
  name: aws-credentials
type: Opaque
data:
  # [!] If using S3 / AWS, change aws-access-key-id and aws-secret-access-key to contain the base64
  #      encoded keys needed to authenticate with the storage specified in migstorage.

  # [!] CAUTION: It's easy to miss the step of base64 encoding your AWS credentials when inputting
  #     them to this secret. since AWS credentials are base64 compatible already. Be _sure_ to run
  #     `echo -n "<key>" | base64 -w 0` on your access and secret key before providing them below.

  # [Note] these credentials will be injected into aws-credentials in the 'velero' namespace.
  aws-access-key-id: M1hIOFpVUlVQVEE1MlBMSzlPRUs=
  aws-secret-access-key: eng1aHd2QzQ0azM2Z0pCWE84N0N0SzdidkRFRXRVd3ZiSEJRSUNBbA==