apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-nfs-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-nfs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: csi-nfs-deployment
  template:
    metadata:
      name: csi-nfs-deployment
      labels:
        name: csi-nfs-deployment
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: csi-nfs-nginx-container
          image: nginx
          command:
            - "/bin/bash"
            - "-c"
            - echo $(date) >> /mnt/nfs/outfile;  while true; do sleep 30; done
          volumeMounts:
            - name: nfs
              mountPath: "/mnt/nfs"
              readOnly: false
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: csi-nfs-pvc