apiVersion: migration.openshift.io/v1alpha1
kind: MigPlan
metadata:
  name: csi-nfs-migplan
  namespace: mig-operator
spec:
  destMigClusterRef:
    name: host
    namespace: mig-operator
  srcMigClusterRef:
    name: source-cluster
    namespace: mig-operator
  indirectImageMigration: true
  indirectVolumeMigration: true
  migStorageRef:
    name: gcp-bucket
    namespace: mig-operator
  namespaces:
    - csi-nfs-namespace
  persistentVolumes:
    - capacity: 5Gi
      name: pvc-41be5fa8-215e-4e6c-b320-668bc237f5d5
      storageClass: csi-nfs-sc
      pvc:
        accessModes:
          - ReadWriteMany
        hasReference: true
        name: csi-nfs-pvc
        namespace: csi-nfs-namespace
      selection:
        action: copy
        copyMethod: snapshot
        storageClass: csi-nfs-sc
      supported:
        actions:
          - copy
          - move
          - skip
        copyMethods:
          - filesystem
          - snapshot