apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: csi-nfs-vs
  labels:
    velero.io/csi-volumesnapshot-class: "true"
spec:
  volumeSnapshotClassName: csi-nfs-snapclass
  source:
    persistentVolumeClaimName: csi-nfs-pvc