apiVersion: velero.io/v1
kind: Restore
metadata: 
 name: migrate-restore
 namespace: mig-operator
spec: 
# backupName: migrate-backup
 backupName: migrate-backup

 includedNamespaces: 
 - cluster-migrate-test-app
# Fill in the resource type to be restored as needed. There is no resource to be excluded under the nginx-example namespace, so enter '*' here.
 includedResources: 
 - '*'
 includeClusterResources: null
# Resources not included in the restoration. Here storageClasses resource types are excluded.
 excludedResources: 
 - storageclasses.storage.k8s.io
# Use the labelSelector selector to select the resource with a specific label. Since there is no need to use the label selector to filter in this sample, please make an annotation here.
# labelSelector:
#   matchLabels:
#     app: nginx
# Set the relationship mapping strategy of the namespace.
 restorePVs: true
