apiVersion: v1
kind: ConfigMap
metadata:
  # any name
  name: change-storage-class-config
  # namespace of velero deployment
  namespace: mig-operator
  labels:
    # this value-less label identifies the ConfigMap as
    # config for a plugin (i.e. the built-in change storage
    # class restore item action plugin)
    velero.io/plugin-config: ""
    # this label identifies the name and kind of plugin
    # that this ConfigMap is for.
    velero.io/change-storage-class: RestoreItemAction
data:
  #<old-sc>:<newsc>
   csi-sc-viettelplugin-ssd: standard-rwo
#  standard: csi-sc-viettelplugin-ssd
#  standard-rwo: csi-sc-viettelplugin-ssd