apiVersion: migration.openshift.io/v1alpha1
kind: MigPlan
metadata:
  name: migplan-example
  namespace: velero
spec:
  destMigClusterRef:
    name: host
    namespace: velero
  indirectImageMigration: true
  indirectVolumeMigration: true
  migStorageRef:
    name: gcp-bucket
    namespace: velero
  namespaces:
    - cluster-migrate-test-app
  persistentVolumes:
    - capacity: 5Gi
      name: pvc-a5253af1-3199-4f75-a853-82832ddd47cb
      storageClass: standard-rwo
      pvc:
        accessModes:
          - ReadWriteOnce
        hasReference: true
        name: pod-demo
        namespace: cluster-migrate-test-app
      selection:
        action: copy
        copyMethod: filesystem
        storageClass: csi-sc-viettelplugin-ssd
      supported:
        actions:
          - copy
        copyMethods:
          - filesystem
  srcMigClusterRef:
    name: source-cluster
    namespace: velero