apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
  namespace: cluster-migrate-test-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-sc-viettelplugin-ssd
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-demo-deployment
  namespace: cluster-migrate-test-app
spec:
  selector:
    matchLabels:
      app: pod-demo
  template:
    metadata:
      labels:
        app: pod-demo
    spec:
     volumes:
      - name: pvc-demo-vol
        persistentVolumeClaim:
         claimName: pvc-demo
     containers:
      - name: pod-demo
        image: nginx
        resources:
         limits:
          cpu: 200m
          memory: 800Mi
         requests:
          cpu: 200m
          memory: 800Mi
        ports:
         - containerPort: 80
           name: "http-server"
        volumeMounts:
         - mountPath: "/usr/share/nginx/html"
           name: pvc-demo-vol
  
---
apiVersion: v1
kind: Service
metadata:
  name: pod-demo-service
  namespace: cluster-migrate-test-app
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: pod-demo
