apiVersion: v1
kind: Secret
metadata:
  name: sa-token-remote
  namespace: velero
type: Opaque
data:
  saToken: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklteENVRlJIWTNsd1FXeDBVVjlVUVVwcU4wVkVNVlZJV0ZWcVQzSkdhRGcxUldWalNtVmlWM0ZmTjBFaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUoyWld4bGNtOGlMQ0pyZFdKbGNtNWxkR1Z6TG1sdkwzTmxjblpwWTJWaFkyTnZkVzUwTDNObFkzSmxkQzV1WVcxbElqb2liV2xuTFdOdmJuUnliMnhzWlhJdGMyRXRjMlZqY21WMElpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVibUZ0WlNJNkltMXBaeTFqYjI1MGNtOXNiR1Z5TFhOaElpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVkV2xrSWpvaVlXRm1OemhrWlRNdFpHVXhZeTAwWVRSakxXRmhOREF0WW1RMVpUa3daRFZpWmpRd0lpd2ljM1ZpSWpvaWMzbHpkR1Z0T25ObGNuWnBZMlZoWTJOdmRXNTBPblpsYkdWeWJ6cHRhV2N0WTI5dWRISnZiR3hsY2kxellTSjkuVzR2U3hrZ1ZCUHBBOEphS2V5c2piLVdwVlJ3TFdaQkIwVEg3djQ4UTVJdUk0cDI5bUc0ZmJOTUg3N0kxSjUzQVVtNmtqYVdQbWpPcHowVmVneVhUeGd3Rkd5Ri1xbXc3UmNRNVdFbzI2OUhSVHpZOTVoRkpndEhtV1JUenFMUGYyNmExTF85TnZZdXVLOVFFc1hUdlNHUHNzQU9uTHVzel9LLTUtTVRVUGRCbU9DblQtM1JVVXpIUE8tTHhBMklCZEtRb1MzTGVXMTNkQUxaX2RzTDdKS3d6UUtMbnlXM0pJN0FGSjV1ZlBMMkhGMUVKZmw1UE81enA2XzRXdlM5NlFvdS14MXhpYmJpLU0wMUZZLWZzRV9SckJrNF8xVm9wak9MNGJxQ2MxRno2QUtVdkF5MnRYWk83Z2FiTmVyam5tQ052dWZZa0x3U1U0UWxDNXdPR3p3



