apiVersion: v1
kind: ServiceAccount
metadata:
  name: mig-controller-sa
  namespace: openshift-migration
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mig-controller-clr
subjects:
- kind: ServiceAccount
  name: mig-controller-sa
  namespace: openshift-migration
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io