apiVersion: migration.openshift.io/v1alpha1
kind: MigPlan
metadata:
  name: nfs-migplan-example
  namespace: velero
spec:
  destMigClusterRef:
    name: host
    namespace: velero
  srcMigClusterRef:
    name: source-cluster
    namespace: velero
  indirectImageMigration: true
  indirectVolumeMigration: true
  migStorageRef:
    name: gcp-bucket
    namespace: velero
  namespaces:
    - nfs-migrate
  persistentVolumes:
    - capacity: 5Gi
      name: pvc-3b4a15fd-8de7-4ff0-bcd3-74461d833809
      storageClass: nfs-csi
      pvc:
        accessModes:
          - ReadWriteMany
        hasReference: true
        name: pvc-demo-nfs-dynamic
        namespace: nfs-migrate
      selection:
        action: copy
        copyMethod: snapshot
        storageClass: nfs-csi
      supported:
        actions:
          - copy
          - move
          - skip
        copyMethods:
          - filesystem
          - snapshot