apiVersion: migration.openshift.io/v1alpha1
kind: MigPlan
metadata:
  name: spec-nfs-migplan-example
  namespace: velero
spec:
  destMigClusterRef:
    name: host
    namespace: velero
  srcMigClusterRef:
    name: source-cluster
    namespace: velero
  indirectImageMigration: true
  indirectVolumeMigration: true
  migStorageRef:
    name: gcp-bucket
    namespace: velero
  namespaces:
    - thanhph3
  persistentVolumes:
    - capacity: 5Gi
      name: spec-nfs-pv
      storageClass: static-nfs-sc
      pvc:
        accessModes:
          - ReadWriteMany
        hasReference: true
        name: pvc-demo-nfs-spec
        namespace: thanhph3
      selection:
        action: move
        storageClass: static-nfs-sc
      supported:
        actions:
          - copy
          - move
          - skip
        copyMethods:
          - filesystem
          - snapshot